// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RapChieuPhim.Areas.Admin.Data;

namespace RapChieuPhim.Migrations
{
    [DbContext(typeof(DPContext))]
    [Migration("20210115065913_yeucaudangnhapAdmin")]
    partial class yeucaudangnhapAdmin
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RapChieuPhim.Areas.Admin.Models.BinhLuanModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Da_xoa")
                        .HasColumnType("bit");

                    b.Property<int>("NguoiDung_ID")
                        .HasColumnType("int");

                    b.Property<string>("Noi_dung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Phim_ID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("NguoiDung_ID");

                    b.HasIndex("Phim_ID");

                    b.ToTable("BinhLuanModel");
                });

            modelBuilder.Entity("RapChieuPhim.Areas.Admin.Models.GheModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Da_chon")
                        .HasColumnType("bit");

                    b.Property<bool>("Da_xoa")
                        .HasColumnType("bit");

                    b.Property<int>("Loai")
                        .HasColumnType("int");

                    b.Property<int>("PhongChieu_ID")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("PhongChieu_ID");

                    b.ToTable("GheModel");
                });

            modelBuilder.Entity("RapChieuPhim.Areas.Admin.Models.HoaDonModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Da_xoa")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Ngay_lap")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiDung_ID")
                        .HasColumnType("int");

                    b.Property<string>("Tong_tien")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("NguoiDung_ID");

                    b.ToTable("HoaDonModel");
                });

            modelBuilder.Entity("RapChieuPhim.Areas.Admin.Models.LichChieuModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Da_xoa")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Ngay")
                        .HasColumnType("datetime2");

                    b.Property<int>("RapPhim_ID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("RapPhim_ID");

                    b.ToTable("LichChieuModel");
                });

            modelBuilder.Entity("RapChieuPhim.Areas.Admin.Models.NguoiDungModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Admin")
                        .HasColumnType("bit");

                    b.Property<bool>("Da_xoa")
                        .HasColumnType("bit");

                    b.Property<string>("Dia_chi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Ngay_sinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasColumnType("nvarchar(11)")
                        .HasMaxLength(11);

                    b.HasKey("ID");

                    b.ToTable("NguoiDungModel");
                });

            modelBuilder.Entity("RapChieuPhim.Areas.Admin.Models.PhimModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Da_xoa")
                        .HasColumnType("bit");

                    b.Property<int>("Gia_ve")
                        .HasColumnType("int");

                    b.Property<string>("Hinh_anh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Luot_xem")
                        .HasColumnType("int");

                    b.Property<string>("Ten_phim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Thoi_luong")
                        .HasColumnType("int");

                    b.Property<string>("Video")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("PhimModel");
                });

            modelBuilder.Entity("RapChieuPhim.Areas.Admin.Models.PhongChieuModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Da_xoa")
                        .HasColumnType("bit");

                    b.Property<int>("RapPhim_ID")
                        .HasColumnType("int");

                    b.Property<string>("Ten_Phong")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("RapPhim_ID");

                    b.ToTable("PhongChieuModel");
                });

            modelBuilder.Entity("RapChieuPhim.Areas.Admin.Models.RapPhimModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Da_xoa")
                        .HasColumnType("bit");

                    b.Property<string>("Dia_chi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten_rap")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("RapPhimModel");
                });

            modelBuilder.Entity("RapChieuPhim.Areas.Admin.Models.TaiKhoanModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Da_xoa")
                        .HasColumnType("bit");

                    b.Property<int>("Loai_tai_khoan")
                        .HasColumnType("int");

                    b.Property<string>("Mat_khau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NguoiDung_ID")
                        .HasColumnType("int");

                    b.Property<string>("Ten_dang_nhap")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("NguoiDung_ID");

                    b.ToTable("TaiKhoanModel");
                });

            modelBuilder.Entity("RapChieuPhim.Areas.Admin.Models.VeXemPhimModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("DaXoa")
                        .HasColumnType("bit");

                    b.Property<int?>("Ghe_ID")
                        .HasColumnType("int");

                    b.Property<int?>("HoaDon_ID")
                        .HasColumnType("int");

                    b.Property<int?>("Phim_ID")
                        .HasColumnType("int");

                    b.Property<int?>("PhongChieu_ID")
                        .HasColumnType("int");

                    b.Property<int?>("RapPhim_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Thoi_gian")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("Ghe_ID");

                    b.HasIndex("HoaDon_ID");

                    b.HasIndex("Phim_ID");

                    b.HasIndex("PhongChieu_ID");

                    b.HasIndex("RapPhim_ID");

                    b.ToTable("VeXemPhimModel");
                });

            modelBuilder.Entity("RapChieuPhim.Areas.Admin.Models.XuatChieuModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Da_xoa")
                        .HasColumnType("bit");

                    b.Property<int>("LichChieu_ID")
                        .HasColumnType("int");

                    b.Property<int>("Phim_ID")
                        .HasColumnType("int");

                    b.Property<string>("Thoi_gian")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("LichChieu_ID");

                    b.HasIndex("Phim_ID");

                    b.ToTable("XuatChieuModel");
                });

            modelBuilder.Entity("RapChieuPhim.Areas.Admin.Models.BinhLuanModel", b =>
                {
                    b.HasOne("RapChieuPhim.Areas.Admin.Models.NguoiDungModel", "idNguoiDung")
                        .WithMany("lstBinhLuan")
                        .HasForeignKey("NguoiDung_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RapChieuPhim.Areas.Admin.Models.PhimModel", "idPhim")
                        .WithMany("lstBinhLuan")
                        .HasForeignKey("Phim_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RapChieuPhim.Areas.Admin.Models.GheModel", b =>
                {
                    b.HasOne("RapChieuPhim.Areas.Admin.Models.PhongChieuModel", "idPhongChieu")
                        .WithMany("lstGhe")
                        .HasForeignKey("PhongChieu_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RapChieuPhim.Areas.Admin.Models.HoaDonModel", b =>
                {
                    b.HasOne("RapChieuPhim.Areas.Admin.Models.NguoiDungModel", "idNguoiDung")
                        .WithMany("lstHoaDon")
                        .HasForeignKey("NguoiDung_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RapChieuPhim.Areas.Admin.Models.LichChieuModel", b =>
                {
                    b.HasOne("RapChieuPhim.Areas.Admin.Models.RapPhimModel", "idRapPhim")
                        .WithMany("lstLichChieu")
                        .HasForeignKey("RapPhim_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RapChieuPhim.Areas.Admin.Models.PhongChieuModel", b =>
                {
                    b.HasOne("RapChieuPhim.Areas.Admin.Models.RapPhimModel", "idRapPhim")
                        .WithMany("lstPhongChieu")
                        .HasForeignKey("RapPhim_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RapChieuPhim.Areas.Admin.Models.TaiKhoanModel", b =>
                {
                    b.HasOne("RapChieuPhim.Areas.Admin.Models.NguoiDungModel", "NguoiDungModel")
                        .WithMany("lstTaiKhoan")
                        .HasForeignKey("NguoiDung_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RapChieuPhim.Areas.Admin.Models.VeXemPhimModel", b =>
                {
                    b.HasOne("RapChieuPhim.Areas.Admin.Models.GheModel", "idGhe")
                        .WithMany("lstVeXemPhim")
                        .HasForeignKey("Ghe_ID");

                    b.HasOne("RapChieuPhim.Areas.Admin.Models.HoaDonModel", "idHoaDon")
                        .WithMany("lstVeXemPhim")
                        .HasForeignKey("HoaDon_ID");

                    b.HasOne("RapChieuPhim.Areas.Admin.Models.PhimModel", "idPhim")
                        .WithMany("lstVeXemPhim")
                        .HasForeignKey("Phim_ID");

                    b.HasOne("RapChieuPhim.Areas.Admin.Models.PhongChieuModel", "idPhongChieu")
                        .WithMany()
                        .HasForeignKey("PhongChieu_ID");

                    b.HasOne("RapChieuPhim.Areas.Admin.Models.RapPhimModel", "idRapPhim")
                        .WithMany("lstVeXemPhim")
                        .HasForeignKey("RapPhim_ID");
                });

            modelBuilder.Entity("RapChieuPhim.Areas.Admin.Models.XuatChieuModel", b =>
                {
                    b.HasOne("RapChieuPhim.Areas.Admin.Models.LichChieuModel", "idLichChieu")
                        .WithMany("lstXuatChieu")
                        .HasForeignKey("LichChieu_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RapChieuPhim.Areas.Admin.Models.PhimModel", "idPhim")
                        .WithMany("lstXuatChieu")
                        .HasForeignKey("Phim_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
