// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RapChieuPhim.Areas.Admin.Data;

namespace RapChieuPhim.Migrations
{
    [DbContext(typeof(DPContext))]
    partial class DPContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("RapChieuPhim.Areas.Admin.Models.ChuDePhimModel", b =>
                {
                    b.Property<int>("idChuDe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("tenChuDe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("trangThaiChuDe")
                        .HasColumnType("int");

                    b.HasKey("idChuDe");

                    b.ToTable("LoaiChuDePhim");
                });

            modelBuilder.Entity("RapChieuPhim.Areas.Admin.Models.PhimModel", b =>
                {
                    b.Property<int>("idPhim")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("anhPhim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("binhluanPhim")
                        .HasColumnType("int");

                    b.Property<int>("idP_ChuDe")
                        .HasColumnType("int");

                    b.Property<string>("motaPhim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ngayDang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tenPhim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("trangThaiPhim")
                        .HasColumnType("int");

                    b.HasKey("idPhim");

                    b.HasIndex("idP_ChuDe");

                    b.ToTable("Phim");
                });

            modelBuilder.Entity("RapChieuPhim.Areas.Admin.Models.PhimModel", b =>
                {
                    b.HasOne("RapChieuPhim.Areas.Admin.Models.ChuDePhimModel", "idChuDe")
                        .WithMany("lstPost")
                        .HasForeignKey("idP_ChuDe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("idChuDe");
                });

            modelBuilder.Entity("RapChieuPhim.Areas.Admin.Models.ChuDePhimModel", b =>
                {
                    b.Navigation("lstPost");
                });
#pragma warning restore 612, 618
        }
    }
}
